version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    ports:
      - "${MYSQL_HOST_PORT:-3306}:3306"
    environment:
      TZ: Asia/Taipei
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: Attendance_System
      MYSQL_USER: user
      MYSQL_PASSWORD: user123
    volumes:
      - mysql_data:/var/lib/mysql
      - ./Attendance_System.sql:/docker-entrypoint-initdb.d/Attendance_System.sql
volumes:
  mysql_data:
